[constants]
dt = 0.05
Omega0 = 4
gamma = 0.1818181818181
gammadia = 0.117
gX = -0.364
xi = 47.0
Gamma = 0.05
Bstart = 6
Bend = -6
E0 = 1.9
eta = 0.0002
uX = 0.01
R = 0.012
EXY = 0.0004
p = 1.65
width = 1.0
B0 = 3
resgamma = 0.1
amp = 10
nElementsX = 256
nElementsY = 256
nElementsZ = 256
xGroupSize = 8
yGroupSize = 8

